CREATE DATABASE VecinAppDb;

USE VecinAppDb;

CREATE TABLE IF NOT EXISTS Discusiones(
IdDiscusion INT PRIMARY KEY AUTO_INCREMENT,
IdVecino INT DEFAULT 0,
Titulo VARCHAR(100) NOT NULL,
Descripcion VARCHAR(500) NOT NULL,
Conclusion VARCHAR(500) DEFAULT '',
Estado TINYINT(1) NOT NULL,
FechaCreacion DATETIME DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS DiscusionComentarios(
IdComentario INT PRIMARY KEY AUTO_INCREMENT,
IdDiscusion INT NOT NULL,
IdVecino INT DEFAULT 0,
Fecha DATETIME NOT NULL,
Comentario VARCHAR(500),
FOREIGN KEY (IdDiscusion) REFERENCES Discusiones(IdDiscusion)
);